"""
This is a constant file that contains the list of Pokemon Data
"""

__author__ = "NEIL EDRIANE LERIN"

from constants.type import TYPE

POKEMON_DATA = [
    {
        "id": 1,
        "name": "Bulbasaur",
        "description": "Seed Pokémon",
        "defense": 49,
        "attack": 49,
        "speed": 45,
        "type": TYPE.GRASS,
        "hp": 100,
        "max_hp": 100,
        "abilities": [
            {
                "index": 1,
                "name": "Tackle",
                "type": TYPE.NORMAL,
                "damage": 40,
                "accuracy": 100,
                "critical": 10,
                "description": "A physical charge attack.",
            },
            {
                "index": 2,
                "name": "Vine Whip",
                "type": TYPE.GRASS,
                "damage": 55,
                "accuracy": 90,
                "critical": 8,
                "description": "Strikes the target with slender vines.",
            },
            {
                "index": 3,
                "name": "Razor Leaf",
                "type": TYPE.GRASS,
                "damage": 75,
                "accuracy": 75,
                "critical": 20,
                "description": "Sharp-edged leaves are launched to slash the foe.",
            },
        ],
    },
    {
        "id": 4,
        "name": "Charmander",
        "description": "Lizard Pokémon",
        "defense": 43,
        "attack": 52,
        "speed": 65,
        "type": TYPE.FIRE,
        "hp": 100,
        "max_hp": 100,
        "abilities": [
            {
                "index": 1,
                "name": "Scratch",
                "type": TYPE.NORMAL,
                "damage": 40,
                "accuracy": 100,
                "critical": 10,
                "description": "Hard claws rake the target.",
            },
            {
                "index": 2,
                "name": "Ember",
                "type": TYPE.FIRE,
                "damage": 65,
                "accuracy": 90,
                "critical": 8,
                "description": "Small flames are shot at the target.",
            },
            {
                "index": 3,
                "name": "Flamethrower",
                "type": TYPE.FIRE,
                "damage": 80,
                "accuracy": 75,
                "critical": 5,  # powerful but low crit
                "description": "The foe is scorched with intense flames.",
            },
        ],
    },
    {
        "id": 7,
        "name": "Squirtle",
        "description": "Tiny Turtle Pokémon",
        "defense": 65,
        "attack": 48,
        "speed": 43,
        "type": TYPE.WATER,
        "hp": 100,
        "max_hp": 100,
        "abilities": [
            {
                "index": 1,
                "name": "Tackle",
                "type": TYPE.NORMAL,
                "damage": 40,
                "accuracy": 100,
                "critical": 10,
                "description": "A full-body charge attack.",
            },
            {
                "index": 2,
                "name": "Water Gun",
                "type": TYPE.WATER,
                "damage": 55,
                "accuracy": 90,
                "critical": 8,
                "description": "Squirts water at the target.",
            },
            {
                "index": 3,
                "name": "Bubble Beam",
                "type": TYPE.WATER,
                "damage": 75,
                "accuracy": 80,
                "critical": 6,
                "description": "A stream of bubbles strikes the target.",
            },
        ],
    },
    {
        "id": 25,
        "name": "Pikachu",
        "description": "Mouse Pokémon",
        "defense": 40,
        "attack": 55,
        "speed": 90,
        "type": TYPE.ELECTRIC,
        "hp": 100,
        "max_hp": 100,
        "abilities": [
            {
                "index": 1,
                "name": "Thunder Shock",
                "type": TYPE.ELECTRIC,
                "damage": 40,
                "accuracy": 100,
                "critical": 10,
                "description": "A jolt of electricity strikes the target.",
            },
            {
                "index": 2,
                "name": "Quick Attack",
                "type": TYPE.NORMAL,
                "damage": 45,
                "accuracy": 100,
                "critical": 15,
                "description": "An extremely fast attack.",
            },
            {
                "index": 3,
                "name": "Thunderbolt",
                "type": TYPE.ELECTRIC,
                "damage": 85,
                "accuracy": 75,
                "critical": 5,
                "description": "A strong electric blast crashes onto the target.",
            },
        ],
    },
]
